### ISSUE TITLE
Selecting a node id does not select all geometries with that id

### ISSUE THREAD

**Issue by dragly** [cognitedata/reveal-viewer#10] opened 2019-05-19 09:31 UTC
Only some parts of the geometries that correspond to the node id are selected (via @f1cognite).

**Comment by anderscognite** [comment] 2019-05-31 15:50
This may be a bug with the backend. @f2cognite I asked you about this, did you find anything?

**Comment by ghost** [comment] 2019-06-03 08:24
I think I looked into it but didn't find anything; but I can double-check if you give me the details again

**Comment by anderscognite** [comment] 2019-06-03 12:09
I just looked at 
```
project: 3ddemo
modelId: 4291994125741328
revisionId: 968271980052890
```

And found that `nodeId` 2570168472089215 has `treeIndex` 15. When I parse the file with `3d-web-parser`, I find the following geometries with `treeIndex` 0:

```
Found 0, 2570168472089215 of type BoxGroup
Found 0, 2570168472089215 of type BoxGroup
Found 0, 4781679390810252 of type BoxGroup
Found 0, 4781679390810252 of type BoxGroup
Found 0, 4781679390810252 of type BoxGroup
Found 0, 4781679390810252 of type BoxGroup
Found 0, 4781679390810252 of type BoxGroup
Found 0, 4781679390810252 of type BoxGroup
Found 0, 1097152192836546 of type BoxGroup
Found 0, 1097152192836546 of type BoxGroup
Found 0, 1097152192836546 of type BoxGroup
Found 0, 1097152192836546 of type BoxGroup
Found 0, 1097152192836546 of type BoxGroup
Found 0, 1097152192836546 of type BoxGroup
Found 0, 2570168472089215 of type BoxGroup
Found 0, 3501626813932326 of type BoxGroup
Found 0, 2570168472089215 of type BoxGroup
Found 0, 2570168472089215 of type BoxGroup
Found 0, 1905926201588721 of type CircleGroup
Found 0, 1905926201588721 of type CircleGroup
Found 0, 1503762993736444 of type CircleGroup
Found 0, 7755540475735041 of type CircleGroup
Found 0, 1905926201588721 of type CircleGroup
Found 0, 1905926201588721 of type CircleGroup
Found 0, 1503762993736444 of type CircleGroup
Found 0, 7755540475735041 of type CircleGroup
Found 0, 1503762993736444 of type CircleGroup
Found 0, 1503762993736444 of type CircleGroup
Found 0, 7755540475735041 of type CircleGroup
Found 0, 7755540475735041 of type CircleGroup
Found 0, 7755540475735041 of type CircleGroup
Found 0, 1905926201588721 of type CircleGroup
Found 0, 1905926201588721 of type CircleGroup
Found 0, 1503762993736444 of type CircleGroup
Found 0, 1503762993736444 of type CircleGroup
Found 0, 7755540475735041 of type CircleGroup
Found 0, 1905926201588721 of type CircleGroup
Found 0, 1905926201588721 of type CircleGroup
Found 0, 1503762993736444 of type CircleGroup
Found 0, 1503762993736444 of type CircleGroup
Found 0, 1503762993736444 of type CircleGroup
Found 0, 1503762993736444 of type CircleGroup
Found 0, 1503762993736444 of type CircleGroup
Found 0, 7755540475735041 of type CircleGroup
Found 0, 1503762993736444 of type CircleGroup
Found 0, 1905926201588721 of type CircleGroup
Found 0, 1905926201588721 of type CircleGroup
Found 0, 1503762993736444 of type CircleGroup
Found 0, 1905926201588721 of type CircleGroup
Found 0, 7755540475735041 of type CircleGroup
Found 0, 7755540475735041 of type CircleGroup
Found 0, 1905926201588721 of type CircleGroup
Found 0, 8585272562056348 of type CircleGroup
Found 0, 7755540475735041 of type CircleGroup
Found 0, 1905926201588721 of type CircleGroup
Found 0, 7755540475735041 of type CircleGroup
Found 0, 1905926201588721 of type CircleGroup
Found 0, 1503762993736444 of type CircleGroup
Found 0, 1905926201588721 of type CircleGroup
Found 0, 7755540475735041 of type CircleGroup
Found 0, 1503762993736444 of type CircleGroup
Found 0, 1503762993736444 of type CircleGroup
Found 0, 1503762993736444 of type CircleGroup
Found 0, 1905926201588721 of type CircleGroup
Found 0, 1905926201588721 of type CircleGroup
Found 0, 7755540475735041 of type CircleGroup
Found 0, 1503762993736444 of type CircleGroup
Found 0, 1503762993736444 of type CircleGroup
Found 0, 1503762993736444 of type CircleGroup
Found 0, 1503762993736444 of type CircleGroup
Found 0, 1503762993736444 of type CircleGroup
Found 0, 1503762993736444 of type CircleGroup
Found 0, 1503762993736444 of type CircleGroup
Found 0, 7755540475735041 of type CircleGroup
Found 0, 1905926201588721 of type CircleGroup
Found 0, 1905926201588721 of type CircleGroup
Found 0, 6830412002659435 of type CircleGroup
Found 0, 6830412002659435 of type CircleGroup
Found 0, 5292074263253086 of type CircleGroup
Found 0, 4409206100046680 of type CircleGroup
Found 0, 4409206100046680 of type CircleGroup
Found 0, 4409206100046680 of type CircleGroup
Found 0, 4409206100046680 of type CircleGroup
Found 0, 4409206100046680 of type CircleGroup
Found 0, 4409206100046680 of type CircleGroup
Found 0, 4409206100046680 of type CircleGroup
Found 0, 5292074263253086 of type CircleGroup
Found 0, 6830412002659435 of type CircleGroup
Found 0, 6830412002659435 of type CircleGroup
Found 0, 4409206100046680 of type CircleGroup
Found 0, 4409206100046680 of type CircleGroup
Found 0, 4409206100046680 of type CircleGroup
Found 0, 5292074263253086 of type CircleGroup
Found 0, 6830412002659435 of type CircleGroup
Found 0, 4409206100046680 of type CircleGroup
Found 0, 6830412002659435 of type CircleGroup
Found 0, 5292074263253086 of type CircleGroup
Found 0, 6830412002659435 of type CircleGroup
Found 0, 7536943307376201 of type CircleGroup
Found 0, 5292074263253086 of type CircleGroup
Found 0, 7536943307376201 of type CircleGroup
Found 0, 6830412002659435 of type CircleGroup
Found 0, 5292074263253086 of type CircleGroup
Found 0, 5292074263253086 of type CircleGroup
Found 0, 6830412002659435 of type CircleGroup
Found 0, 4409206100046680 of type CircleGroup
Found 0, 6830412002659435 of type CircleGroup
Found 0, 6830412002659435 of type CircleGroup
Found 0, 4409206100046680 of type CircleGroup
Found 0, 5292074263253086 of type CircleGroup
Found 0, 4409206100046680 of type CircleGroup
Found 0, 4409206100046680 of type CircleGroup
Found 0, 4409206100046680 of type CircleGroup
Found 0, 4409206100046680 of type CircleGroup
Found 0, 6830412002659435 of type CircleGroup
Found 0, 6830412002659435 of type CircleGroup
Found 0, 5292074263253086 of type CircleGroup
Found 0, 4409206100046680 of type CircleGroup
Found 0, 4409206100046680 of type CircleGroup
Found 0, 6830412002659435 of type CircleGroup
Found 0, 6830412002659435 of type CircleGroup
Found 0, 5292074263253086 of type CircleGroup
Found 0, 5292074263253086 of type CircleGroup
Found 0, 5292074263253086 of type CircleGroup
Found 0, 4409206100046680 of type CircleGroup
Found 0, 4409206100046680 of type CircleGroup
Found 0, 5292074263253086 of type CircleGroup
Found 0, 4409206100046680 of type CircleGroup
Found 0, 6830412002659435 of type CircleGroup
Found 0, 6830412002659435 of type CircleGroup
Found 0, 5292074263253086 of type CircleGroup
Found 0, 4409206100046680 of type CircleGroup
Found 0, 6830412002659435 of type CircleGroup
Found 0, 6830412002659435 of type CircleGroup
Found 0, 1905926201588721 of type ConeGroup
...
```

This comes right from the parser. One of these circles look like this from the protobuf data:
<img width="703" alt="Screenshot 2019-06-03 14 08 33" src="https://user-images.githubusercontent.com/34239077/58800804-1d8b3200-8609-11e9-938b-2f195b824d8c.png">

Can you check with your tools if there is a parsing problem or the file has bad data?

**Comment by ghost** [comment] 2019-06-03 13:09
Indeed seems like the file is bad. I've opened an [issue in the backend](https://github.com/cognitedata/3d-optimizer/issues/384) for this.

**Comment by ghost** [comment] 2019-07-02 15:42
I can't seem to reproduce this with the files that are produced by the optimizer today (that is, version 5 or 6). Since the model in question had file format version 4, I suggest we don't spend time trying to fix this, and instead reprocess the models that have this problem.

**Comment by anderscognite** [comment] 2019-07-02 17:09
That was protobuf btw!

**Comment by anderscognite** [comment] 2019-07-17 10:39
This bug was fixed in the backend I think.

**Closed as completed by anderscognite** 2019-07-17 10:39 UTC
Labels: bug, High priority
