### ISSUE TITLE
Clicking on nodes in model

### ISSUE THREAD

**Issue by thomaslein** [cognitedata/reveal-viewer#15] opened 2019-05-27 07:57 UTC
Viewer version: 5.0.8

Certain nodes gives TypeError. Seems like the viewer is trying to iterate over something that doesn't exist. 

<img width="569" alt="Screenshot 2019-05-22 at 22 19 58" src="https://user-images.githubusercontent.com/871556/58404468-7553f700-8065-11e9-99aa-7afafd466b74.png">
<img width="250" alt="Screenshot 2019-05-22 at 22 20 20" src="https://user-images.githubusercontent.com/871556/58404469-7553f700-8065-11e9-87b3-24ff78065753.png">
<img width="399" alt="Screenshot 2019-05-22 at 22 20 56" src="https://user-images.githubusercontent.com/871556/58404470-75ec8d80-8065-11e9-9da8-19b2a76041f1.png">

**Comment by anderscognite** [comment] 2019-05-31 07:38
Thanks for reporting! It seems to be a problem here: https://github.com/cognitedata/3d-web-parser/blob/master/src/geometry/InstancedMeshGroup.ts#L279

In principle, an instanced mesh group should not be asked for bounding box for a given treeIndex if parsing went ok, so this is probably bad parsing somewhere. If you can reproduce this easily, can you also provide camera position and camera target? I couldn't find the geometry you wanted to click on.

**Comment by ragnhildlarsen** [comment] 2019-05-31 08:01
cameraPosition:
Vector3 {x: -24.151217625498855, y: 153.5262346638636, z: -105.13413649533467}
x: -24.151217625498855
y: 153.5262346638636
z: -105.13413649533467

cameraTarget:
Vector3 {x: -38.10570059816541, y: -390.00600525616113, z: -155.57626046176446}
x: -38.10570059816541
y: -390.00600525616113
z: -155.57626046176446

Find this on top of the XMT:
![Screenshot 2019-05-31 at 09 59 30 (2)](https://user-images.githubusercontent.com/50363113/58690901-ed366000-838a-11e9-8de4-a162165e70aa.png)

And zoom into the red thing to find this and click at the "bottom":
![Screenshot 2019-05-31 at 09 59 40 (2)](https://user-images.githubusercontent.com/50363113/58690942-0212f380-838b-11e9-9b60-da76d4e4a6af.png)

**Comment by anderscognite** [comment] 2019-05-31 15:42
Fixed in 3d-viewer 5.1.1 by some internal code and https://github.com/cognitedata/3d-web-parser/pull/64

**Closed as completed by anderscognite** 2019-05-31 15:42 UTC
